const Strings = {
  title_app: 'Agricola Land',
  title_list: 'Farmer List',
  desc_list: 'List of farmer',
  label_btn_add: 'Add Farmer',
  label_btn_load: 'Load More',
  label_collapse: 'Collapse',
  title_add: 'Add Farmer',
  desc_add: 'Form add for create a farmer',
  title_detail: 'Detail Farmer',
  desc_detail: 'Form detail for view a farmer',
  title_edit: 'Edit Farmer',
  desc_edit: 'Form edit for update a farmer',
  label_col_no: 'No',
  value_col_no: 'no',
  label_col_name: 'Farmer Name',
  value_col_name: 'name',
  placeholder_name: 'Enter Name',
  label_col_id_number: 'ID Card Number',
  placeholder_id_number: 'Enter ID Card Number',
  value_col_id_number: 'idCardNumber',
  label_col_birthdate: 'Birthdate',
  value_col_birthdate: 'birthDate',
  placeholder_birthdate: 'Enter Birthdate',
  msg_required: 'Please fill in this field.',
  msg_min_3_char: 'must be at least 3 characters long',
  msg_not_valid: 'Please fill with valid value',
  label_col_action: 'Action',
  value_col_action: 'action',
  label_act_view: 'View',
  label_act_edit: 'Edit',
  label_act_delete: 'Delete',
  label_btn_edit: 'Save Edit',
  label_open_profile: 'Open Settings',
  value_open_profile: 'open',
  label_act_sign_out: 'Sign Out',
  msg_success_sign_out: 'Your sign out successfully, Welcome back!',
  title_success_add: 'Farmer Added Successfully',
  msg_success_add: 'You have successfully added a new farmer',
  title_success_edit: 'Edit Farmer Successfully',
  msg_success_edit: 'The farmer has been successfully editted from the system',
  title_success_delete: 'Farmer Deleted Successfully',
  msg_success_delete:
    'The farmer has been successfully deleted from the system',
  id_button_no_dialog: 'button-modal-farmer',
  id_button_yes_dialog: 'button-modal-farmer',
  label_btn_no_modal: 'No, Decline',
  label_btn_yes_add_modal: 'Yes, Add',
  label_btn_yes_edit_modal: 'Yes, Edit',
  label_btn_yes_delete_modal: 'Yes, Delete',
  title_modal_add: 'Add Farmer',
  msg_modal_add:
    'Please make sure there are no mistakes and typos when filling the information.',
  title_modal_edit: 'Edit Farmer',
  msg_modal_edit:
    'Please make sure there are no mistakes and typos when Editting the information.',
  title_modal_delete: 'Delete Farmer',
  msg_modal_delete:
    'Are you sure you want to delete #name ? This action cannot be undone',
};

export default Strings;
