const strings = {
  title_app: 'Agricola Land',
  title_list: 'Farmer List',
  desc_list: 'List of farmer',
  label_btn_add: 'Add Farmer',
  title_add: 'Add Farmer',
  desc_add: 'Form add for create a farmer',
  title_detail: 'Detail Farmer',
  desc_detail: 'Form detail for view a farmer',
  title_edit: 'Edit Farmer',
  desc_edit: 'Form edit for update a farmer',
  label_col_no: 'No',
  value_col_no: 'no',
  label_col_name: 'Farmer Name',
  value_col_name: 'name',
  placeholder_name: 'Enter Name',
  label_col_id_number: 'ID Card Number',
  placeholder_id_number: 'Enter ID Card Number',
  value_col_id_number: 'idCardNumber',
  label_col_birthdate: 'Birthdate',
  value_col_birthdate: 'birthDate',
  placeholder_birthdate: 'Enter Birthdate',
  msg_required: 'Please fill in this field.',
  msg_min_3_char: 'must be at least 3 characters long',
  msg_not_valid: 'Please fill with valid value',
  label_col_action: 'Action',
  value_col_action: 'action',
  label_act_view: 'View',
  label_act_edit: 'Edit',
  label_act_delete: 'Delete',
  label_btn_edit: 'Save Edit',
};

export default strings;
